baseURL = "https://procionegobbo.it/"
canonifyURLs = true
relativeURLs = false

theme = "ananke"
defaultContentLanguage = "it"
defaultContentLanguageInSubdir = false

[params]
  # Abilita Table of Contents in tutti i post
  toc = true
  # Abilita callout shortcode
  enableCallout = true
  
  # Ananke specific parameters
  site_logo = "/images/ProcionegobboSmall.png"
  favicon = "/favicon.png"

[languages]

[languages.it]
  languageName = "Italiano"
  weight = 1
  title = "Federico Maiorini"
  contentDir = "content/it"
  languageCode = "it-it"

  [languages.it.params]
  mainSections = ["blog", "gdr", "scrittura"]

[languages.en]
  languageName = "English"
  weight = 2
  title = "Federico Maiorini"
  contentDir = "content/en"
  languageCode = "en-us"

  [languages.en.params]
  mainSections = ["blog"]



[markup.goldmark.renderer]
  unsafe = true

[params.footer]
  since = 2025
  customText = "Federico Maiorini"

[params.colorScheme]
    # light, dark, auto
    default = "light"
    toggle = false
    auto = false

[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 1

[[menu.main]]
  identifier = "gdr"
  name = "GDR"
  url = "/gdr/"
  weight = 2

[[menu.main]]
  identifier = "scrittura"
  name = "Scrittura"
  url = "/scrittura/"
  weight = 3

[[menu.main]]
  identifier = "chi-sono"
  name = "Chi sono"
  url = "/chi-sono/"
  weight = 4

## Multilingua: menu e mainSections ottimizzati

[[languages.en.menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 1

[[languages.en.menu.main]]
  identifier = "gdr"
  name = "RPG"
  url = "/gdr/"
  weight = 2

[[languages.en.menu.main]]
  identifier = "scrittura"
  name = "Writing"
  url = "/scrittura/"
  weight = 3

[[languages.en.menu.main]]
  identifier = "about"
  name = "About"
  url = "/en/about/"
  weight = 4

[services]
  [services.googleAnalytics]
    ID = 'G-7T0LHSKHVD'
  [services.disqus]
    shortname = 'procionegobbo-it'
